/**
 * Client-side mirror of `packages/auction/src/ladder.cairo`.
 *
 * Every function here must agree with Cairo bit for bit — a drift in a domain tag or
 * field order makes every bid this client produces unprovable. `test/conformance.test.ts`
 * pins them against vectors generated by `snforge test test_vectors`.
 */
import { hash, shortString } from "starknet";

const poseidon = (xs: bigint[]): bigint =>
  BigInt(hash.computePoseidonHashOnElements(xs.map((x) => "0x" + x.toString(16))));

const tag = (s: string): bigint => BigInt(shortString.encodeShortString(s));

export const CHAIN_TAG = tag("VICKREY_CHAIN:V1");
export const UP_SEED_TAG = tag("VICKREY_UP_SEED:V1");
export const DOWN_SEED_TAG = tag("VICKREY_DOWN_SEED:V1");
export const CLAIM_TAG = tag("VICKREY_CLAIM:V1");
export const BID_ROOT_TAG = tag("VICKREY_BID_ROOT:V1");

/** Matches `ladder::MAX_LEVELS`. */
export const MAX_LEVELS = 1024;

export const step = (auctionId: bigint, claimCommitment: bigint, x: bigint): bigint =>
  poseidon([CHAIN_TAG, auctionId, claimCommitment, x]);

export function stepN(
  auctionId: bigint,
  claimCommitment: bigint,
  x: bigint,
  n: number,
): bigint {
  let acc = x;
  for (let i = 0; i < n; i++) acc = step(auctionId, claimCommitment, acc);
  return acc;
}

/** The bid's only public identity. The preimage authorizes every later claim. */
export const claimCommitmentOf = (claimSecret: bigint): bigint =>
  poseidon([CLAIM_TAG, claimSecret]);

export const upSeed = (seed: bigint): bigint => poseidon([UP_SEED_TAG, seed]);
export const downSeed = (seed: bigint): bigint => poseidon([DOWN_SEED_TAG, seed]);

export const upAnchor = (
  auctionId: bigint,
  claimCommitment: bigint,
  seed: bigint,
  level: number,
): bigint => stepN(auctionId, claimCommitment, upSeed(seed), level);

export const downAnchor = (
  auctionId: bigint,
  claimCommitment: bigint,
  seed: bigint,
  level: number,
  numLevels: number,
): bigint => stepN(auctionId, claimCommitment, downSeed(seed), numLevels - 1 - level);

/** Witness proving `level >= t`. A bid can only vouch for bounds it actually meets. */
export function witnessAtOrAbove(
  auctionId: bigint,
  claimCommitment: bigint,
  seed: bigint,
  level: number,
  t: number,
): bigint {
  if (t > level) throw new Error(`bid at level ${level} cannot prove >= ${t}`);
  return stepN(auctionId, claimCommitment, upSeed(seed), level - t);
}

/** Witness proving `level <= t`. */
export function witnessAtOrBelow(
  auctionId: bigint,
  claimCommitment: bigint,
  seed: bigint,
  level: number,
  t: number,
): bigint {
  if (t < level) throw new Error(`bid at level ${level} cannot prove <= ${t}`);
  return stepN(auctionId, claimCommitment, downSeed(seed), t - level);
}

export const verifyAtOrAbove = (
  auctionId: bigint,
  claimCommitment: bigint,
  anchor: bigint,
  t: number,
  witness: bigint,
): boolean => stepN(auctionId, claimCommitment, witness, t) === anchor;

export const verifyAtOrBelow = (
  auctionId: bigint,
  claimCommitment: bigint,
  anchor: bigint,
  numLevels: number,
  t: number,
  witness: bigint,
): boolean =>
  t < numLevels && stepN(auctionId, claimCommitment, witness, numLevels - 1 - t) === anchor;

export const extendBidRoot = (
  prev: bigint,
  index: number,
  claimCommitment: bigint,
  up: bigint,
  down: bigint,
): bigint => poseidon([BID_ROOT_TAG, prev, BigInt(index), claimCommitment, up, down]);
