pub const CALLER_NOT_PRIVACY: felt252 = 'CALLER_NOT_PRIVACY';
pub const ZERO_OUT_AMOUNT: felt252 = 'ZERO_OUT_AMOUNT';
pub const AMOUNT_OVERFLOW: felt252 = 'OUT_AMOUNT_OVERFLOW';
pub const APPROVE_FAILED: felt252 = 'ERC20_APPROVE_FAILED';
